name: Setup Node
description: Setup Node

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
        cache: yarn

    - run: yarn install --frozen-lockfile
      shell: bash
