name: Setup Node
description: Setup Node

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "18"

    - id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - run: yarn install
      shell: bash
