name: Setup Node
description: Setup Node

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v6

    - uses: actions/setup-node@v7
      with:
        node-version: lts/*
        cache: pnpm

    - run: pnpm install --frozen-lockfile
      shell: bash
