version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: "/.github/actions/build-api-doc"
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: "/.github/actions/setup-node"
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: "/.github/actions/setup-python"
    schedule:
      interval: daily
