header: |
  ### Documentation

  See: https://v2.nonebot.dev
template: |
  ### ðŸ’« Changes

  $CHANGES
category-template: "### $TITLE"
name-template: "Release v$RESOLVED_VERSION ðŸŒˆ"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
categories:
  - title: "ðŸ’¥ Breaking Changes"
    labels:
      - "Breaking"
  - title: "ðŸš€ Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "ðŸ› Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "ðŸ“ Documentation"
    labels:
      - "documentation"
  - title: "ðŸ» Plugin Publish"
    label: "Plugin"
  - title: "ðŸ» Bot Publish"
    label: "Bot"
  - title: "ðŸ» Adapter Publish"
    label: "Adapter"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
