template: $CHANGES
category-template: "### $TITLE"
name-template: "Release v$RESOLVED_VERSION ðŸŒˆ"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE [@$AUTHOR](https://github.com/$AUTHOR) ([#$NUMBER]($URL))"
change-title-escapes: '\<&'
exclude-labels:
  - "dependencies"
  - "skip-changelog"
categories:
  - title: "ðŸ’¥ ç ´åæ€§å˜æ›´"
    labels:
      - "Breaking"
  - title: "ðŸš€ æ–°åŠŸèƒ½"
    labels:
      - "feature"
      - "enhancement"
  - title: "ðŸ› Bug ä¿®å¤"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "ðŸ“ æ–‡æ¡£"
    labels:
      - "documentation"
  - title: "ðŸ’« æ‚é¡¹"
  - title: "ðŸ» æ’ä»¶å‘å¸ƒ"
    label: "Plugin"
  - title: "ðŸ» æœºå™¨äººå‘å¸ƒ"
    label: "Bot"
  - title: "ðŸ» é€‚é…å™¨å‘å¸ƒ"
    label: "Adapter"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
