name: 发布插件
title: "Plugin: {name}"
description: 发布插件到 NoneBot 官方商店
labels: ["Plugin", "Publish"]
body:
  - type: checkboxes
    id: tutorial
    attributes:
      label: 插件发布教程
      description: 我已阅读 [NoneBot 插件发布流程指导](https://nonebot.dev/docs/developer/plugin-publishing)
      options:
        - label: 我已阅读 NoneBot 插件发布流程指导
          required: true

  - type: input
    id: pypi
    attributes:
      label: PyPI 项目名
      description: PyPI 项目名
      placeholder: e.g. nonebot-plugin-xxx
    validations:
      required: true

  - type: input
    id: module
    attributes:
      label: 插件模块名
      description: 加载插件时所使用的模块名称
      placeholder: e.g. nonebot_plugin_apscheduler
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: 标签
      description: 标签
      placeholder: 'e.g. [{"label": "标签名", "color": "#ea5252"}]'
      value: "[]"
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: 插件配置项
      description: 插件配置项
      render: dotenv
      placeholder: |
        # e.g.
        # KEY=VALUE
        # KEY2=VALUE2
