name: Setup Python
description: Setup Python

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.12"
  env-dir:
    description: Environment directory
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}
        working-directory: ${{ inputs.env-dir }}
        cache-dependency-glob: |
          ./uv.lock
          ${{ inputs.env-dir }}/uv.lock

    - run: |
        cd ${{ inputs.env-dir }}
        uv sync --all-extras --locked
      shell: bash
