name: Setup Python
description: Setup Python

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.10"

runs:
  using: "composite"
  steps:
    - name: Install poetry
      run: pipx install poetry

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'poetry'

    - run: poetry install -E all
      shell: bash
