name: Setup Python
description: Setup Python

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.9"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
        architecture: "x64"
        cache: 'poetry'

    - name: Install poetry
      shell: bash
      run: pipx install poetry

    - run: poetry install -E all
      shell: bash
