/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorial: [
    {
      type: "category",
      label: "开始",
      collapsible: false,
      items: ["index", "quick-start", "editor-support", "question"],
    },
    // {
    //   type: "category",
    //   label: "开始",
    //   items: [
    //     {
    //       type: "autogenerated",
    //       dirName: "start",
    //     },
    //   ],
    // },
    {
      type: "category",
      label: "指南",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorial",
        },
      ],
    },
    {
      type: "category",
      label: "深入",
      items: [
        {
          type: "autogenerated",
          dirName: "appendices",
        },
      ],
    },
    // {
    //   type: "category",
    //   label: "进阶",
    //   items: [
    //     {
    //       type: "autogenerated",
    //       dirName: "advanced",
    //     },
    //   ],
    // },
  ],
  api: [{ type: "autogenerated", dirName: "api" }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
